import { DEFAULT_QUESTIONS } from "./questions";
import type { Settings } from "./types";

export const DEFAULT_SETTINGS: Settings = {
  questions: DEFAULT_QUESTIONS,
  rules: [
    {
      id: "r-experience",
      label: "Au moins 3 ans d'expérience",
      target: "experience",
      operator: "includes",
      value: "3 à 5 ans",
      points: 20,
      mode: "bonus",
      enabled: true,
    },
    {
      id: "r-dispo",
      label: "Disponible rapidement",
      target: "disponibilite",
      operator: "equals",
      value: "Immédiatement",
      points: 15,
      mode: "bonus",
      enabled: true,
    },
    {
      id: "r-cdi",
      label: "Ouvert au CDI",
      target: "contrat",
      operator: "includes",
      value: "CDI",
      points: 15,
      mode: "bonus",
      enabled: true,
    },
    {
      id: "r-salaire",
      label: "Prétentions dans le budget",
      target: "salaire",
      operator: "lte",
      value: "45000",
      points: 20,
      mode: "bonus",
      enabled: true,
    },
    {
      id: "r-cv",
      label: "CV fourni",
      target: "file",
      operator: "has_file",
      value: "cv",
      points: 10,
      mode: "required",
      enabled: true,
    },
    {
      id: "r-motivation",
      label: "Motivation rédigée",
      target: "motivation",
      operator: "answered",
      value: "",
      points: 20,
      mode: "bonus",
      enabled: true,
    },
  ],
  threshold: 60,
  hideDisqualified: false,
  defaultSort: "score",
  jobTitle: "Candidature spontanée",
  companyName: "Valeur Ajoutée",
  intro:
    "Dix questions, cinq minutes. Prenez le temps de répondre franchement : c'est ce qui nous permet de bien vous lire.",
};
