import type { Question } from "./types";

/** Seed questionnaire. Editable from Réglages → Questionnaire once the app runs. */
export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: "poste",
    label: "Quel poste visez-vous ?",
    hint: "Choisissez celui qui correspond le mieux à votre candidature.",
    type: "single",
    required: true,
    options: [
      "Assistant·e administratif·ve",
      "Chargé·e de clientèle",
      "Commercial·e terrain",
      "Comptable",
      "Développeur·se",
      "Autre poste",
    ],
  },
  {
    id: "experience",
    label: "Combien d'années d'expérience avez-vous sur ce type de poste ?",
    type: "single",
    required: true,
    options: ["Moins d'un an", "1 à 3 ans", "3 à 5 ans", "5 à 10 ans", "Plus de 10 ans"],
  },
  {
    id: "disponibilite",
    label: "À partir de quand êtes-vous disponible ?",
    type: "single",
    required: true,
    options: ["Immédiatement", "Sous 1 mois", "Sous 2 à 3 mois", "Plus de 3 mois"],
  },
  {
    id: "contrat",
    label: "Quels types de contrat vous intéressent ?",
    hint: "Plusieurs réponses possibles.",
    type: "multi",
    required: true,
    options: ["CDI", "CDD", "Alternance", "Stage", "Freelance", "Temps partiel"],
  },
  {
    id: "rythme",
    label: "Quel rythme de travail vous convient ?",
    type: "single",
    required: true,
    options: ["Sur site", "Hybride", "Télétravail complet", "Peu importe"],
  },
  {
    id: "competences",
    label: "Quelles compétences maîtrisez-vous ?",
    hint: "Sélectionnez tout ce qui s'applique.",
    type: "multi",
    required: true,
    options: [
      "Relation client",
      "Gestion administrative",
      "Comptabilité",
      "Négociation commerciale",
      "Suite bureautique",
      "Outils numériques / CRM",
      "Gestion de projet",
      "Encadrement d'équipe",
    ],
  },
  {
    id: "langues",
    label: "Quelles langues pratiquez-vous en contexte professionnel ?",
    type: "multi",
    options: ["Français", "Anglais", "Espagnol", "Allemand", "Italien", "Arabe", "Autre"],
  },
  {
    id: "salaire",
    label: "Quelles sont vos prétentions salariales annuelles brutes ?",
    hint: "En euros, sur 12 mois. Une fourchette approximative suffit.",
    type: "number",
    required: true,
    min: 0,
    max: 300000,
    unit: "€ brut / an",
    placeholder: "32000",
  },
  {
    id: "realisation",
    label: "Racontez une réalisation dont vous êtes fier·e.",
    hint: "Le contexte, ce que vous avez fait, le résultat. Quelques lignes suffisent.",
    type: "textarea",
    required: true,
    placeholder: "J'ai repris un portefeuille de 120 clients et…",
  },
  {
    id: "motivation",
    label: "Pourquoi souhaitez-vous nous rejoindre ?",
    hint: "Ce qui vous attire dans le poste, et ce que vous venez y chercher.",
    type: "textarea",
    required: true,
    placeholder: "Ce qui m'intéresse, c'est…",
  },
];
