import type { Question } from "./types";

/**
 * Questionnaire de départ, taillé pour le recrutement en magasin Kiabi.
 * Modifiable depuis Réglages → Questionnaire une fois l'application en route.
 */
export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: "poste",
    label: "Quel poste vous intéresse ?",
    hint: "Choisissez celui qui correspond le mieux à votre candidature.",
    type: "single",
    required: true,
    options: [
      "Conseiller·ère de vente",
      "Hôte·sse de caisse et accueil",
      "Employé·e libre-service (réassort, rangement)",
      "Préparateur·rice de commandes Click & Collect",
      "Responsable de rayon",
      "Peu importe, je suis ouvert·e",
    ],
  },
  {
    id: "contrat",
    label: "Quels types de contrat vous intéressent ?",
    hint: "Plusieurs réponses possibles.",
    type: "multi",
    required: true,
    options: ["CDI", "CDD", "Alternance", "Stage", "Job étudiant", "Intérim"],
  },
  {
    id: "temps",
    label: "Quel temps de travail cherchez-vous ?",
    type: "single",
    required: true,
    options: [
      "Temps plein (35 h)",
      "Temps partiel (24 à 30 h)",
      "Temps partiel (15 à 20 h)",
      "Quelques heures, surtout le week-end",
      "Peu importe",
    ],
  },
  {
    id: "disponibilite",
    label: "À partir de quand êtes-vous disponible ?",
    type: "single",
    required: true,
    options: ["Immédiatement", "Sous 2 semaines", "Sous 1 mois", "Sous 2 à 3 mois", "Plus tard"],
  },
  {
    id: "creneaux",
    label: "Sur quels créneaux pouvez-vous travailler ?",
    hint: "Le magasin vit surtout le samedi et pendant les temps forts. Soyez franc·he : c'est ce qui nous évite de vous proposer des horaires impossibles.",
    type: "multi",
    required: true,
    options: [
      "En semaine, la journée",
      "En soirée, jusqu'à la fermeture",
      "Le samedi",
      "Le dimanche (ouvertures exceptionnelles)",
      "Pendant les soldes et la rentrée",
      "Pendant les vacances scolaires",
    ],
  },
  {
    id: "experience",
    label: "Quelle est votre expérience de la vente ou du commerce ?",
    type: "single",
    required: true,
    options: [
      "Aucune expérience",
      "Moins d'un an",
      "1 à 3 ans",
      "3 à 5 ans",
      "Plus de 5 ans",
    ],
  },
  {
    id: "atouts",
    label: "Qu'est-ce que vous savez déjà faire ?",
    hint: "Sélectionnez tout ce qui s'applique. Rien n'est éliminatoire : le reste s'apprend en magasin.",
    type: "multi",
    required: true,
    options: [
      "Accueillir et conseiller un client",
      "Tenir une caisse",
      "Ranger et réassortir un rayon",
      "Gérer une réserve et des stocks",
      "Préparer des commandes",
      "Mettre en valeur un produit (merchandising)",
      "Encadrer une équipe",
      "Parler une deuxième langue",
    ],
  },
  {
    id: "trajet",
    label: "Combien de temps mettez-vous pour venir au magasin ?",
    hint: "En minutes, porte à porte, avec le moyen de transport que vous utiliseriez tous les jours.",
    type: "number",
    required: true,
    min: 0,
    max: 240,
    unit: "minutes",
    placeholder: "20",
  },
  {
    id: "relation_client",
    label: "Racontez une fois où vous avez rendu service à quelqu'un.",
    hint: "En magasin, au travail, en stage, dans une association : le contexte importe peu. Quelques lignes suffisent.",
    type: "textarea",
    required: true,
    placeholder: "Une cliente cherchait une tenue pour…",
  },
  {
    id: "motivation",
    label: "Pourquoi Kiabi ?",
    hint: "Ce qui vous attire dans le poste, et ce que vous venez y chercher.",
    type: "textarea",
    required: true,
    placeholder: "Ce qui m'intéresse, c'est…",
  },
];
